package s_mach.datadiff

import org.scalatest.{Matchers, FlatSpec}

class SimpleDiffTest extends FlatSpec with Matchers {

  val aDiff = implicitly[Diff[Int,Int]]

  "SimpleDiff.diff" must "detect differences between the old and new value" in {
    1 diff 2 should equal(Some(2))
    1 diff 1 should equal(None)
  }

  "SimpleDiff.patch" must "apply changes to an old value to achieve new value" in {
    val d = 1 diff 2
    1 patch d should equal(2)
  }

  "SimpleDiff.valuetoPatch" must "make a change from a value" in {
    aDiff.valueToPatch(1) should equal(1)
  }

  "SimpleDiff.canPatchToValue" must "always be true" in {
    aDiff.canPatchToValue(1) should equal(true)
  }

  "SimpleDiff.patchToValue" must "make a value from a change" in {

    aDiff.patchToValue(1) should equal(1)
  }

  "SimpleDiff.patchToValue" must "always successfully convert a patch generated by valueToPatch back to value" in {
    aDiff.patchToValue(aDiff.valueToPatch(1)) should equal(1)
  }
}
